# Generated by Django 4.2.25 on 2026-06-22 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageimage',
            name='image',
            field=models.ImageField(upload_to='chat_app/message_images'),
        ),
    ]
