# Generated by Django 4.2.25 on 2026-06-22 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
